#!/bin/sh
#
#	do ROT13 substituion cipher
#	written by Jan Engelhardt, 2013
#
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of the WTF Public License version 2 or
#	(at your option) any later version.
#

if [ "$#" -gt 1 ]; then
	cat "$@" | tr 'A-Za-z' 'N-ZA-Mn-za-m';
elif [ "$#" -eq 1 ]; then
	exec tr 'A-Za-z' 'N-ZA-Mn-za-m' <"$1";
else
	exec tr 'A-Za-z' 'N-ZA-Mn-za-m';
fi;
