.TH hxtools 7 "2008-11-11" "hxtools" "hxtools"
.SH Name
hxtools \(em Suite of various shell scripts and other stuff
.SH Description
.PP
\fBhxtools\fP is Jan Engelhardt's accumulated tool collection.
.SH Components
.PP
\fBbin2c\fP(1) \(en embed data files into C as variables
.PP
\fBbsvplay\fP(1) \(en convert BASICA music files to PCM
.PP
\fBcctypeinfo\fP(1) \(en show sizes of some C types on the implementation it
was compiled with
.PP
\fBcheckbrack\fP(1) \(en check parenthesis and bracket count
.PP
\fBclock_info\fP(1) \(en print info about system clocks
.PP
\fBclt2bdf\fP(1) \(en convert Consoleet text bitmaps to BDF or SFD
.PP
\fBclt2pbm\fP(1) \(en convert Consoleet text bitmaps to PBM Portable Bitmap
.PP
\fBcwdiff\fP(1) \(en run wdiff with color
.PP
\fBdeclone\fP(1) \(en break hardlinks
.PP
\fBdiff2php\fP(1) \(en transform patch to self\-serving PHP file
.PP
\fBdoxygen\-kernel\-filter\fP(1) \(en a doxygen filter for doxygen to
understand KernelDoc
.PP
\fBextract_d3pkg\fP(1) \(en extract Descent3 PKG files
.PP
\fBextract_dxhog\fP(1) \(en extract Descent HOG files
.PP
\fBextract_f3pod\fP(1) \(en extract Fury3 POD files
.PP
\fBextract_qupak\fP(1) \(en extract Quake2 PACK files
.PP
\fBfd0ssh\fP(1) \(en pipe for password-over-stdin support to ssh
.PP
\fBfilenameconv\fP(1) \(en convert file name encoding
.PP
\fBfnt2bdf\fP(1) \(en convert VGA raw fonts to X11 BDF
.PP
\fBfxterm\fP(1) \(en start xterm with VGA color palette
.PP
\fBgit\-author\-stat\fP(1) \(en show commit author statistics of a git repository
.PP
\fBgit\-blame\-stat\fP(1) \(en show per-line author statistics of a git
repository
.PP
\fBgit\-forest\fP(1) \(en display the commit history forest
.PP
\fBgit\-revert\-stats\fP(1) \(en show reverting statistics of a git repository
.PP
\fBgit\-track\fP(1) \(en set up branch for tracking a remote
.PP
\fBgpsh\fP(1) \(en grep tracklists and play audio files
.PP
\fBgraph\-fanout\fP(1) \(en fan a tree (for graphviz)
.PP
\fBgraph\-lchain\fP(1) \(en remove circles in graphs using longest-chaining
method
.PP
\fBhcdplay\fP(1) \(en control autonomous CDDA playback using Linux ioctls
.PP
\fBlogontime\fP(8) \(en show cumulative logon time from wtmp
.PP
\fBmailsplit\fP(1) \(en split an mbox into single files
.PP
\fBman2html\fP(1) \(en convert nroff manpages to HTML
.PP
\fBmkvappend\fP(1) \(en concatenate multiple files into one Matroska container
file
.PP
\fBmod2opus\fP(1) \(en wrapper for tracker module/MIDI to Opus transcoding
.PP
\fBnetload\fP(8) \(en show utilization of network interface
.PP
\fBofl\fP(1) \(en open file lister
.PP
\fBpaddrspacesize\fP(1) \(en print size of processes' address spaces
.PP
\fBpcmdiff\fP(1) \(en proof-of-concept raw PCM deltifier
.PP
\fBpegrep\fP(1) \(en multi-line perl-regexp grep
.PP
\fBpeicon\fP(1) \(en extract icon resources from PE files
.PP
\fBpesubst\fP(1) \(en perl-regexp stream substitution (replaces sed for
substitutions)
.PP
\fBpmap_dirty\fP(1) \(en print amount of dirty pages of a process
(somewhat indicative of its memory use)
.PP
\fBpng2wx.pl\fP(1) \(en transform arbitrary files into C++ files for wxWidgets
.PP
\fBprintcaps\fP(1) \(en print currently active process capabilities
.PP
\fBproc_iomem_count\fP(1) \(en show MMIO region sizes
.PP
\fBproc_stat_signal\fP(1) \(en decode /proc/self/stat for signal status
.PP
\fBpshtreads\fP(1) \(en alternative experiment to ps(1) involving thread
display
.PP
\fBqplay\fP(1) \(en convert QBASIC play strings to PCM
.PP
\fBqtar\fP(1) \(en faster interface to tar with file ordering
.PP
\fBraregetty\fP(8) \(en local login program for remote hosts
.PP
\fBrecursive_lower\fP(1) \(en recursively lowercase all filenames
.PP
\fBrot13\fP(1) \(en shortcut to invoke tr(1) for ROT13
.PP
\fBrpmdep.pl\fP(1) \(en read RPM dependencies and output a graph
.PP
\fBsourcefuncsize\fP(1) \(en statistical analysis of code
.PP
\fBspec\-beautifier\fP(1) \(en program to clean up RPM .spec files
.PP
\fBssa2srt\fP(1) \(en convert SubStation Alpha (SSA) subtitles to SubRip (SRT)
.PP
\fBstxdb\fP(1) \(en A/V file database
.PP
\fBsu1\fP(8) \(en what sudo should have done
.PP
\fBsysinfo\fP(1) \(en print IRC\-style system information banner
.PP
\fBtailhex\fP(1) \(en hex dumper with tail\-following support
.PP
\fButmp_register\fP(1) \(en make entries in the utmp/wtmp database
.PP
\fBvcsaview\fP(8) \(en display a screen dump in VCSA format
.PP
\fBvfontas\fP(1) \(en VGA font file assembler
.PP
\fBwktimer\fP(1) \(en work timer
.PP
\fBxcp\fP(1) \(en proof-of-concept cp(1) with alternate copying mechanisms
.PP
\fBxfs_irecover\fP(8) \(en recover lost inodes from XFS filesystems
.SH Removed components
.PP
Some helpers have been recently removed because they have found better
equivalents.
.PP
\fBgit\-export\-patch\fP. Replaced by `git format\-patch \-M \-M` (can be
chained to mail through `git send\-email ... \-\-format-patch \-M \-M`). The
TortoiseSVN hack that git\-export\-patch offered was dropped without
replacement.
.PP
\fBgit\-new\-root\fP. Replaced by `git checkout --orphan; rm -Rf`.
.PP
\fBomixer\fP. Replaced by the utility "amixer".
.PP
\fBoplay\fP. Replaced by the utility "aplay".
.PP
\fBorec\fP. Replaced by the utility "arecord".
.PP
\fBfduphl\fP. Replaced by the system utility "hardlink".
