#!/bin/bash
# colorize ip(8) output

ip "$@" | perl -lpe \
'
s{(?<=\w) +}{ }g;
s{^(\d+:\s+)(\w+):}{$1\e[0;1m$2\e[1;30m:};
s{\b(link/\w+|dev|via|proto|src|advmss|metric|hoplimit|inet6|inet|peer|valid_lft|preferred_lft|scope|mtu|qdisc)\b}
{\e[0;32m$1\e[1;30m}g;
s{.*}{\e[1;30m$&\e[0m};
';
